import { useState, useEffect } from 'react';
import { api } from '../services/api';
import Sidebar from '../components/Sidebar';
import MainChat from '../components/MainChat';
import '../index.css';

export default function Dashboard() {
    const [conversations, setConversations] = useState([]);
    const [activeConvId, setActiveConvId] = useState(null);
    const [messages, setMessages] = useState([]);
    const [isLoading, setIsLoading] = useState(false);

    useEffect(() => {
        loadConversations();
    }, []);

    useEffect(() => {
        if (activeConvId) {
            loadMessages(activeConvId);
        } else {
            setMessages([]);
        }
    }, [activeConvId]);

    const loadConversations = async () => {
        try {
            const data = await api.get('/conversations');
            setConversations(data);
            if (data.length > 0 && !activeConvId) {
                // optionally auto select the first one: setActiveConvId(data[0].id);
            }
        } catch (e) {
            console.error("Failed to load conversations", e);
        }
    };

    const loadMessages = async (id) => {
        try {
            const data = await api.get(`/conversations/${id}/messages`);
            setMessages(data);
        } catch (e) {
            console.error("Failed to load messages", e);
        }
    };

    const handleNewConversation = async () => {
        try {
            const data = await api.post('/conversations', { title: 'Nova Conversa' });
            setConversations([data, ...conversations]);
            setActiveConvId(data.id);
        } catch (e) {
            console.error("Failed to create conversation", e);
        }
    };

    const handleSendMessage = async (text) => {
        let currentConvId = activeConvId;
        
        // Se ainda não há id ativo, crie a conversa dinamicamente
        if (!currentConvId) {
            try {
                const data = await api.post('/conversations', { title: text.substring(0, 30) });
                setConversations([data, ...conversations]);
                currentConvId = data.id;
                setActiveConvId(currentConvId);
            } catch (e) {
                console.error("Failed to create conversation auto", e);
                return;
            }
        }

        // Adiciona otimisticamente a msg ao front
        const userMsg = { role: 'user', content: text };
        setMessages(prev => [...prev, userMsg]);
        setIsLoading(true);

        try {
            const res = await api.post(`/conversations/${currentConvId}/chat`, { question: text });
            
            // Re-fetch messages and conversations to get updated title generated by backend
            await loadConversations();
            
            setMessages(prev => [...prev, {
                role: 'assistant',
                content: res.answer,
                context: res.context
            }]);
        } catch (e) {
            console.error("Erro ao enviar msg", e);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="dashboard-container">
            <Sidebar 
                conversations={conversations} 
                activeConvId={activeConvId} 
                onSelectConversation={setActiveConvId}
                onNewConversation={handleNewConversation}
            />
            <div className="main-content">
                <MainChat 
                    messages={messages} 
                    onSendMessage={handleSendMessage} 
                    isLoading={isLoading} 
                />
            </div>
        </div>
    );
}
